spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://115.159.153.114:3306/statistics?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    username: root
    password: timeseller
  jpa:
    show-sql: true

logging:
  pattern:
    console: "%d  %msg%n"
    file: E:\miniplog\minip.log
    level: debug
