spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/minip?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 121151
  jpa:
    show-sql: true

logging:
  pattern:
    console: "%d  %msg%n"
    file: E:\miniplog\minip.log
    level: debug
