spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/minip?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    username: root
    password: vv199652
  jpa:
    show-sql: true

logging:
  pattern:
    console: "%d  %msg%n"
    file: E:\miniplog\minip.log
    level: debug
