spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://115.159.153.114:3306/statistics?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: timeseller
  jpa:
    show-sql: true
server:
  port: 8088
